@default:
	just --choose

build: edinburgh2022
	#!/usr/bin/env bash
	set -euxo pipefail
	cp _redirects dist/

deploy: build
	op run -- pnpm exec wrangler pages publish ./dist --project-name kubehuddle

edinburgh2022:
	#!/usr/bin/env bash
	set -euxo pipefail
	mkdir -p dist/2022/edinburgh
	cd 2022/edinburgh
	just download-schedule
	pnpm install
	ASTRO_BASE_PATH="/2022/edinburgh" pnpm build
	cp -r dist/* ../../dist/2022/edinburgh
