@default:
	just --choose

build: edinburgh2022 toronto2023
	#!/usr/bin/env bash
	set -euxo pipefail
	cp _redirects dist/

deploy: build
	op signin --account rawkodeacademy
	op run -- pnpm exec wrangler pages publish ./dist --project-name kubehuddle

edinburgh2022:
	#!/usr/bin/env bash
	set -euxo pipefail
	mkdir -p dist/2022/edinburgh
	cd 2022/edinburgh
	just download-schedule
	pnpm install
	ASTRO_BASE_PATH="/2022/edinburgh" pnpm build
	cp -r dist/* ../../dist/2022/edinburgh

toronto2023:
	#!/usr/bin/env bash
	set -euxo pipefail
	mkdir -p dist/2023/toronto
	cd 2023/toronto
	just download-schedule
	pnpm install
	ASTRO_BASE_PATH="/2023/toronto" pnpm build
	cp -r dist/* ../../dist/2023/toronto
