.PHONY: download-schedule
download-schedule:
	mkdir -p ./data
	curl -fsSL -o ./data/schedule.json https://sessionize.com/api/v2/habhr2k7/view/GridSmart
	curl -fsSL -o ./data/speakers.json https://sessionize.com/api/v2/habhr2k7/view/Speakers
